version: '3.9'
services:
  office-roulette:
    build:
      context: ../.
      dockerfile: Dockerfile
      tags:
        - office-roulette:latest
    image: office-roulette:latest
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Helsinki
      - OR_DB_HOST=office-roulette-db
      - OR_DB_USERNAME=oruser
      - OR_DB_PASSWORD=password_123
      - OR_DB_SSLMODE=disable
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      office-roulette-db:
        condition: service_healthy

  office-roulette-db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ordb
      - POSTGRES_USER=oruser
      - POSTGRES_PASSWORD=password_123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 3
